server:
  tomcat:
    uri-encoding: UTF-8
  port: 8090
  shutdown:
    grace-period: 5000

spring:
  application:
    name: user-api
  config:
    import: classpath:daemon.yml
    profiles:
      include:
        - daemon
      group:
        local: daemon-local
        dev: daemon-dev




grpc:
  server:
    port: 9898
  shutdownGrace: 30


logging:
  level:
    io:
      r2dbc:
        pool: DEBUG
    org:
      springframework:
        r2dbc: DEBUG