// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package com.grpc.lib;

public interface CreateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string fullName = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string confirmPassword = 4;</code>
   * @return The confirmPassword.
   */
  java.lang.String getConfirmPassword();
  /**
   * <code>string confirmPassword = 4;</code>
   * @return The bytes for confirmPassword.
   */
  com.google.protobuf.ByteString
      getConfirmPasswordBytes();
}
