// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package com.grpc.lib;

public interface DeleteUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
