// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package com.grpc.lib;

public interface UpdateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string fullName = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
