// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package com.grpc.lib;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserByEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserByEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user-service.proto\"&\n\025GetUserByEmailRe" +
      "quest\022\r\n\005email\030\001 \001(\t\" \n\022GetUserByIdReque" +
      "st\022\n\n\002id\030\001 \001(\003\"_\n\021CreateUserRequest\022\r\n\005e" +
      "mail\030\001 \001(\t\022\020\n\010fullName\030\002 \001(\t\022\020\n\010password" +
      "\030\003 \001(\t\022\027\n\017confirmPassword\030\004 \001(\t\"1\n\021Updat" +
      "eUserRequest\022\n\n\002id\030\001 \001(\003\022\020\n\010fullName\030\002 \001" +
      "(\t\"\037\n\021DeleteUserRequest\022\n\n\002id\030\001 \001(\003\"M\n\014U" +
      "serResponse\022\n\n\002id\030\001 \001(\003\022\r\n\005email\030\002 \001(\t\022\020" +
      "\n\010fullName\030\003 \001(\t\022\020\n\010password\030\004 \001(\t2\376\001\n\013U" +
      "serService\022.\n\010findById\022\023.GetUserByIdRequ" +
      "est\032\r.UserResponse\0224\n\013findByEmail\022\026.GetU" +
      "serByEmailRequest\032\r.UserResponse\022+\n\006crea" +
      "te\022\022.CreateUserRequest\032\r.UserResponse\022+\n" +
      "\006update\022\022.UpdateUserRequest\032\r.UserRespon" +
      "se\022/\n\ndeleteById\022\022.DeleteUserRequest\032\r.U" +
      "serResponseB\020\n\014com.grpc.libP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetUserByEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUserByEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserByEmailRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_GetUserByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetUserByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserRequest_descriptor,
        new java.lang.String[] { "Email", "FullName", "Password", "ConfirmPassword", });
    internal_static_UpdateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUserRequest_descriptor,
        new java.lang.String[] { "Id", "FullName", });
    internal_static_DeleteUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeleteUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteUserRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserResponse_descriptor,
        new java.lang.String[] { "Id", "Email", "FullName", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
