spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: local
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  # apply spring-bus with rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  # setting local embedded-redis
  redis:
    host: localhost
    port: 6470
    timeout: 5000

server:
  tomcat:
    uri-encoding: UTF-8
  #random port
  port: 0
  shutdown:
    grace-period: 5000

grpc:
  server:
    port: 9898
  shutdownGrace: 30

eureka:
  #Load Balancer
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


logging:
  level:
    com.mall.userservice: DEBUG
    com:
      mall:
        userservice:
          process:
            user:
              client: DEBUG
    io:
      r2dbc:
        pool: DEBUG
    org:
      springframework:
        r2dbc: DEBUG
        data:
          r2dbc:
            connectionfactory: DEBUG
  file:
    path: D:/logs/

jwt:
  secret-key: testkyo
  expires-minutes: 1440 # 24hr

# apply actuator refresh, health, beans, httptrace, busrefresh
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh


daemon:
  nick-name: kyo local