# 스프링 부트 2.4 이전에는 default 영역으로 인식되었지만,
# 스프링 부트 2.4 부터는 제일 마지막 정의된 내용으로 덮어씌워진다.
spring:
  config:
    activate:
      on-profile: local

daemon:
  nick-name: Developer User local
  root-uri: "http://127.0.0.1:8080"

---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:mariadb://172.17.0.2:49168/user
    username: mall
    password: test!1234
    # config from https://github.com/r2dbc/r2dbc-pool
    pool:
      initialSize: 10
      maxSize: 100
      #30 minutes
      maxIdleTime: PT30M
      validationQuery: SELECT 1

daemon:
  nick-name: Developer User dev
  root-uri: "http://172.17.0.2:9090"



