server:
  port: 8888

spring:
  application:
    name: config-service
  banner:
    charset: UTF-8
    location: classpath:/banner.txt
  config:
    activate:
      on-profile: dev
  # apply spring-bus with rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyoDaddy/repo-spring-cloud-mall.git
          username: kyoDaddy
          password: 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
          default-label: main

# apply actuator health,busrefresh
management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh
