# 스프링 부트 2.4 이전에는 default 영역으로 인식되었지만,
# 스프링 부트 2.4 부터는 제일 마지막 정의된 내용으로 덮어씌워진다.
spring:
  config:
    activate:
      on-profile: local

  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/spring-cloud-repo/navtive-file-repo-spring-cloud/mall

daemon:
  nick-name: Developer Item local
  root-uri: "http://127.0.0.1:8080"

---
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyoDaddy/repo-spring-cloud-mall.git
          username: kyoDaddy
          password: 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
          default-label: main

daemon:
  nick-name: Developer Item dev
  root-uri: "http://172.17.0.2:9090"



